version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  
  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    restart: always
    environment:
      CONNECTION_STRING: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/"
      DBNAME: "TRUST"
      SERVER_PORT: 8080
      SERVER_DEBUG: true