EnvVarsNotFound = "env vars {} is None"
ErrorIsExists = "Login: {} already exists"
ErrorBodyJSON = "json must contain: fname, lname, login, password, role, data"
ErrorBodyLoginIsEmpty = "login param is empty"
ErrorData = "JSON is Null"